ProjectInAndOut/Models/ErrorViewModel.cs
namespace ProjectInAndOut.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectInAndOut/Models/Expense.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectInAndOut.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; } 

        [DisplayName("Expense name")]
        [Required]
        public string? ExpenseName { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public int Amount { get; set; }  

        [DisplayName("Expense Type")]
        public int? ExpenseTypeId { get; set; }
        [ForeignKey("ExpenseTypeId")]
        public virtual ExpenseType? ExpenseType { get; set; }  
    }
}

ProjectInAndOut/Models/ExpenseType.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectInAndOut.Models
{
    public class ExpenseType
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string? Name { get; set; }
    }
}

ProjectInAndOut/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ProjectInAndOut.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public string Borrower { get; set; }
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public string? Lender { get; set; }

        [DisplayName("Item name")]
        public string? ItemName { get; set; }
    }
}

ProjectInAndOut/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectInAndOut.Controllers
{
    public class AppointmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
           
        }
    }
}

ProjectInAndOut/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectInAndOut.Data;
using ProjectInAndOut.Models;

namespace ProjectInAndOut.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ExpenseController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            IEnumerable<Expense> objList = _db.Expenses;
            return View(objList);
            
        }

        //Get create
        public IActionResult Create()
        {
            return View();
        }

        //Post Create, which means posting the form data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expense obj)
        {
            if(ModelState.IsValid)
            {
                _db.Expenses.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj); 
        }


       


        //To get the Delete id
       
        public IActionResult Delete(int? id)
        {


            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Expenses.Find(id);

            if(obj == null)
            {
                return NotFound();
            }

           
            return View(obj);


        }


        //Post Delete an item, which means removing from database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {

            var obj = _db.Expenses.Find(id);

            if (obj == null)
            {
                return NotFound();
            }


            _db.Expenses.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

ProjectInAndOut/Controllers/ExpenseTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectInAndOut.Data;
using ProjectInAndOut.Models;

namespace ProjectInAndOut.Controllers
{
    public class ExpenseTypeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ExpenseTypeController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            IEnumerable<ExpenseType> objList = _db.ExpenseTypes;
            return View(objList);

        }

        //Get create
        public IActionResult Create()
        {
            return View();
        }

        //Post Create, which means posting the form data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpenseTypes.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }





        //To get the Delete data and display it in a form
        // the id helps in getting the exact one we want to delete

        public IActionResult Delete(int? id)
        {


            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.ExpenseTypes.Find(id);

            if (obj == null)
            {
                return NotFound();
            }


            return View(obj);


        }


        //Post Delete an item, which means removing from database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {

            var obj = _db.ExpenseTypes.Find(id);

            if (obj == null)
            {
                return NotFound();
            }


            _db.ExpenseTypes.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }


        //To get the data we want to update and display it in a form
        // the id helps in getting the exact one we want to update

        public IActionResult Update(int? id)
        {


            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.ExpenseTypes.Find(id);

            if (obj == null)
            {
                return NotFound();
            }


            return View(obj);


        }


        //Updating our Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpenseTypes.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

    }
}

ProjectInAndOut/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectInAndOut.Models;
using System.Diagnostics;

namespace ProjectInAndOut.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectInAndOut/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectInAndOut.Data;
using ProjectInAndOut.Models;

namespace ProjectInAndOut.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ItemController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Items;
            return View(objList);
        }

        //Get create
        public IActionResult Create()
        {
            return View();
        }

        //Post Create, which means posting the form data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _db.Items.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProjectInAndOut/Views/Appointment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index 101</h1>

ProjectInAndOut/Views/Expense/Create.cshtml
@model ProjectInAndOut.Models.Expense

<form method="post" asp-action="Create">
   <div class="border p-3">
       <div asp-validation-summary="All" class="text-danger">

       </div>
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Add Expense</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-6">
                       <label asp-for="ExpenseName"></label>
                   </div>
                   <div class="col-6">
                        <label asp-for="Amount"></label>

                   </div>
              

               </div>

                  <div class="form-group row">
                   <div class="col-6">
                       <input asp-for="ExpenseName" class="form-control" />
                      <span asp-validation-for="ExpenseName"></span>

                   </div>
                   <div class="col-6">
                        <input asp-for="Amount" class="form-control" />
                         <span asp-validation-for="Amount"></span>

                   </div>
                

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-info w-75" value="Create" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-danger w-75" asp-controller="Item" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

ProjectInAndOut/Views/Expense/Delete.cshtml
@model ProjectInAndOut.Models.Expense

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
   <div class="border p-3">
       <div asp-validation-summary="All" class="text-danger">

       </div>
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Delete Expense</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-6">
                       <label asp-for="ExpenseName"></label>
                   </div>
                   <div class="col-6">
                        <label asp-for="Amount"></label>

                   </div>
              

               </div>

                  <div class="form-group row">
                   <div class="col-6">
                       <input asp-for="ExpenseName" disabled class="form-control" />
                

                   </div>
                   <div class="col-6">
                        <input asp-for="Amount" disabled class="form-control" />

                   </div>
                

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-danger w-75" value="delete" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-success w-75" asp-controller="Item" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

ProjectInAndOut/Views/Expense/Index.cshtml
@model IEnumerable<ProjectInAndOut.Models.Expense>

 <div class="container p-3">
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">
            Expenses List
        </h2>
</div>
    <div class="col-6 text-right">
            <a asp-area="" asp-controller="Expense" asp-action="Create" class="btn btn-primary">Create New Expense</a>
</div>
</div>
<br/>

    @if(Model.Count() > 0){
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Expense Name</th>
                     <th>Amount</th>
                     <th>Expense Type</th>
                     <th>Changes</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var expense in Model)
               {
                       <tr>
                        <td style="width:25%">@expense.ExpenseName</td>
                        <td style="width:25%">@expense.Amount</td>
                        <td style="width:25%">@expense.ExpenseType?.Name</td>
                         <td style="width:25%">
                             <div class="w-100 btn-group" role="group">
                                 <a asp-area="" asp-controller="Expense" asp-action="Update" asp-route-Id="@expense.Id" class="btn btn-primary mx-1">Update</a>
                                 <a asp-area="" asp-controller="Expense" asp-action="Delete" asp-route-Id="@expense.Id" class="btn btn-danger mx-1">Delete</a>

                             </div>

                         </td>

                    </tr>
                   
               }
            </tbody>
        </table>
    }else{
                   <h1>No Item created yet</h1>
               }
</div>

ProjectInAndOut/Views/Expense/Update.cshtml
@model ProjectInAndOut.Models.Expense

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden/>
   <div class="border p-3">
 
       </div>
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Update Expense</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-4">
                       <label asp-for="ExpenseName"></label>
                   </div>
                   <div class="col-4">
                        <label asp-for="Amount"></label>

                   </div>
              
                   <div class="col-4">
                        <label asp-for="ExpenseType"></label>

                   </div>

               </div>

                  <div class="form-group row">
                   <div class="col-4">
                       <input asp-for="ExpenseName" class="form-control" />
                      <span asp-validation-for="ExpenseName"></span>

                   </div>
                   <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                         <span asp-validation-for="Amount"></span>

                   </div>

                       <div class="col-4">
                        <select asp-for="ExpenseTypeId" asp-items="@ViewBag.TypeDropDown" class="form-control" >
                            <option selected> --Select Expense Type-- </option>
                        </select>
                        <span asp-validation-for="ExpenseTypeId"></span>

                   </div>
                

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-info w-75" value="Update" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-danger w-75" asp-controller="Expense" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

ProjectInAndOut/Views/ExpenseType/Create.cshtml
@model ProjectInAndOut.Models.ExpenseType

<form method="post" asp-action="Create">
   <div class="border p-3">
       <div asp-validation-summary="All" class="text-danger">

       </div>
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Add Expense Type</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-6">
                       <label asp-for="Name"></label>
                   </div>
                 
              

               </div>

                  <div class="form-group row">
                   <div class="col-6">
                       <input asp-for="Name" class="form-control" />
                      <span asp-validation-for="Name"></span>

                   </div>
                
                

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-info w-75" value="Create" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-danger w-75" asp-controller="ExpenseType" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

ProjectInAndOut/Views/ExpenseType/Delete.cshtml
@model ProjectInAndOut.Models.ExpenseType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
   <div class="border p-3">
       <div asp-validation-summary="All" class="text-danger">

       </div>
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Delete Expense Type</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-6">
                       <label asp-for="Name"></label>
                   </div>
                
              

               </div>

                  <div class="form-group row">
                   <div class="col-6">
                       <input asp-for="Name" disabled class="form-control" />
                

                   </div>
                 
                

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-danger w-75" value="delete" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-success w-75" asp-controller="ExpenseType" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

ProjectInAndOut/Views/ExpenseType/Index.cshtml
@model IEnumerable<ProjectInAndOut.Models.ExpenseType>

 <div class="container p-3">
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">
            Expenses Type List
        </h2>
</div>
    <div class="col-6 text-right">
            <a asp-area="" asp-controller="ExpenseType" asp-action="Create" class="btn btn-primary">Create New Expense Type</a>
</div>
</div>
<br/>

    @if(Model.Count() > 0){
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                     <th>Changes</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
               {
                       <tr>
                        <td style="width:35%">@obj.Name</td>
                         <td style="width:30%">
                             <div class="w-100 btn-group" role="group">
                                 <a asp-area="" asp-controller="ExpenseType" asp-action="Update" asp-route-Id="@obj.Id" class="btn btn-primary mx-1">Update</a>
                                 <a asp-area="" asp-controller="ExpenseType" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-1">Delete</a>

                             </div>

                         </td>

                    </tr>
                   
               }
            </tbody>
        </table>
    }else{
                   <h1>No Item created yet</h1>
               }
</div>

ProjectInAndOut/Views/ExpenseType/Update.cshtml
@model ProjectInAndOut.Models.ExpenseType

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden/>
   <div class="border p-3">
 
       </div>
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Update Expense Type</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-6">
                       <label asp-for="Name"></label>
                   </div>
               
              

               </div>

                  <div class="form-group row">
                   <div class="col-6">
                       <input asp-for="Name" class="form-control" />
                      <span asp-validation-for="Name"></span>

                   </div>
                  
                   </div>
                

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-info w-75" value="Update" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-danger w-75" asp-controller="ExpenseType" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

ProjectInAndOut/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectInAndOut/Views/Item/Create.cshtml
@model ProjectInAndOut.Models.Item

<form method="post" asp-action="Create">
   <div class="border p-3">
       <div class="form-group row">
           <h2 class="text-black-50 pl-3">Add Item</h2>
       </div>
       <div class="row">
           <div class="col-12">
               <div class="form-group row">
                   <div class="col-4">
                       <label asp-for="ItemName"></label>
                   </div>
                   <div class="col-4">
                        <label asp-for="Borrower"></label>

                   </div>
                   <div class="col-4">
                       <label asp-for="Lender"></label>

                   </div>

               </div>

                  <div class="form-group row">
                   <div class="col-4">
                       <input asp-for="ItemName" class="form-control" />
                   </div>
                   <div class="col-4">
                        <input asp-for="Borrower" class="form-control" />
                   </div>
                   <div class="col-4">
                     <input asp-for="Lender" class="form-control" />
                   </div>

               </div>
               
                  <div class="form-group row mt-4">
                   <div class="col-8 offset-2 row">
                       <div class="col">
                       <input type="submit" class="btn btn-info w-75" value="Create" />
                   </div>
                 <div class="col">
                       <a class=" btn btn-danger w-75" asp-controller="Item" asp-action="Index">Back</a>
                   </div>
                   </div>
  

               </div>
           </div>

       </div>
   </div>
</form>

ProjectInAndOut/Views/Item/Index.cshtml
@model IEnumerable<ProjectInAndOut.Models.Item>

 <div class="container p-3">
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">
            Borrowed Items List
        </h2>
</div>
    <div class="col-6 text-right">
            <a asp-area="" asp-controller="Item" asp-action="Create" class="btn btn-primary">Create New Item</a>
</div>
</div>
<br/>

    @if(Model.Count() > 0){
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Item Name</th>
                     <th>Borrower</th>
                      <th>Lender</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
               {
                       <tr>
                        <td style="width:30%">@item.ItemName</td>
                        <td style="width:30%">@item.Borrower</td>
                        <td style="width:30%">@item.Lender</td>
                    </tr>
                   
               }
            </tbody>
        </table>
    }
</div>

ProjectInAndOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectInAndOut</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectInAndOut.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectInAndOut</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">My Expenses</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseType" asp-action="Index">My Expense Type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjectInAndOut - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>